services:
  mysql:
    image: mysql:9.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petclinic -d petclinic"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    networks:
      - jenkins-net

networks:
  jenkins-net:
    name: 16_jenkins_try_jenkins-net
    external: true



    # This is the docker-compose.yml inside your Git repository
services:
  postgres:
    image: 'postgres:15.4'
    restart: always
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    # Add this entire healthcheck block
    
    networks:
      - jenkins-net

networks:
  jenkins-net:
    name: 16_jenkins_try_jenkins-net
    external: true